# Generated by Django 6.1 on 2026-08-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWING', 'Reviewing'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview Scheduled'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
    ]
