# Generated by Django 6.1 on 2026-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_interview_date_application_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_link',
            field=models.URLField(blank=True, help_text='Zoom/Google Meet link for the interview', null=True),
        ),
    ]
